# Generated by Django 2.1.5 on 2019-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0003_auto_20190128_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete_part',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='no_of_programmer',
            field=models.IntegerField(default=0),
        ),
    ]
