# Generated by Django 2.1.5 on 2019-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0004_auto_20190207_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
